# Generated by Django 5.0.6 on 2024-05-15 22:44

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='LicensePlate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plate_number', models.CharField(max_length=8, validators=[django.core.validators.RegexValidator(message='Enter a valid license plate number. Examples: 00AA00 or 00-00-AA', regex='^([0-9]{2}[A-Z]{2}[0-9]{2}|[0-9]{2}-[0-9]{2}-[A-Z]{2})$')])),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='license_plates', to='cars.customer')),
            ],
        ),
    ]
