# Generated by Django 5.0.6 on 2024-05-19 23:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='licenseplate',
            unique_together={('customer', 'plate_number')},
        ),
    ]
