# Generated by Django 5.0.6 on 2024-05-19 23:26

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0002_alter_licenseplate_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='licenseplate',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='licenseplate',
            name='plate_number',
            field=models.CharField(max_length=8, unique=True, validators=[django.core.validators.RegexValidator(message='Enter a valid license plate number. Examples: 00AA00 or 00-00-AA', regex='^([0-9]{2}[A-Z]{2}[0-9]{2}|[0-9]{2}-[0-9]{2}-[A-Z]{2})$')]),
        ),
    ]
